
import { Personnel, Rank, Role, User } from './types';

export const INITIAL_SUPER_ADMIN: Omit<User, 'password'> = {
  id: 'super-admin-01',
  firstName: 'Super',
  lastName: 'Admin',
  email: 'superadmin@bjmp.gov.ph',
  role: Role.SUPER_ADMIN,
  rank: Rank.JDIR,
  isActive: true,
  mustChangePassword: true,
  createdAt: new Date().toISOString(),
};

export const INITIAL_ADMIN: Omit<User, 'password'> = {
  id: 'default-admin-01',
  firstName: 'System',
  lastName: 'Admin',
  email: 'admin@bjmp.gov.ph',
  role: Role.ADMIN,
  rank: Rank.SJO4,
  isActive: true,
  mustChangePassword: true,
  createdAt: new Date().toISOString(),
};

export const MOCK_OFFICES = [
  'Regional Office',
  'Tacloban City Jail',
  'Ormoc City Jail',
  'Baybay City Jail',
  'Maasin City Jail',
  'Sogod District Jail',
];

export const MOCK_DESIGNATIONS = [
  'Warden',
  'Chief Escort',
  'Admin Officer',
  'Searcher',
  'Custodial Officer',
  'HR NCO',
];

export const TRAINING_TYPES = [
  'JBRC',
  'JJLC',
  'JSLC',
  'JOCC',
  'JOOC',
  'JOBC',
  'JOAC',
  'PSOSEC',
];

export const INITIAL_PERSONNEL: Personnel[] = [
  {
    id: 'p-1001',
    rank: Rank.JINSP,
    lastName: 'Mendoza',
    firstName: 'Ricardo',
    middleName: 'Santos',
    extension: '',
    gender: 'Male',
    officeAssignment: ['Tacloban City Jail'],
    designation: ['Warden'],
    education: 'BS Criminology',
    eligibility: 'RA 1080',
    dateOfBirth: '1985-03-15',
    dateOfAppointment: '2010-06-01',
    trainingType: 'JOCC',
    dateOfLastPromotion: '2022-01-15',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1002',
    rank: Rank.SJO4,
    lastName: 'Villanueva',
    firstName: 'Tessie',
    middleName: 'Cruz',
    extension: '',
    gender: 'Female',
    officeAssignment: ['Regional Office'],
    designation: ['Chief Escort'],
    education: 'BS Psychology',
    eligibility: 'CSC Professional',
    dateOfBirth: '1978-08-22',
    dateOfAppointment: '2005-09-15',
    trainingType: 'PSOSEC',
    dateOfLastPromotion: '2021-05-20',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1003',
    rank: Rank.SJO3,
    lastName: 'Garcia',
    firstName: 'Paolo',
    middleName: 'Reyes',
    extension: '',
    gender: 'Male',
    officeAssignment: ['Ormoc City Jail'],
    designation: ['Admin Officer'],
    education: 'BS IT',
    eligibility: 'CSC Professional',
    dateOfBirth: '1982-11-05',
    dateOfAppointment: '2008-02-10',
    trainingType: 'JOAC',
    dateOfLastPromotion: '2023-03-01',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1004',
    rank: Rank.SJO2,
    lastName: 'Corpuz',
    firstName: 'Benjamin',
    middleName: 'Lopez',
    extension: '',
    gender: 'Male',
    officeAssignment: ['Baybay City Jail'],
    designation: ['Investigator'],
    education: 'BS Criminology',
    eligibility: 'RA 1080',
    dateOfBirth: '1988-01-12',
    dateOfAppointment: '2012-07-01',
    trainingType: 'JOBC',
    dateOfLastPromotion: '2020-12-15',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1005',
    rank: Rank.SJO1,
    lastName: 'Lim',
    firstName: 'Sarah',
    middleName: 'Tan',
    extension: '',
    gender: 'Female',
    officeAssignment: ['Maasin City Jail'],
    designation: ['Jail Nurse'],
    education: 'BS Nursing',
    eligibility: 'RA 1080',
    dateOfBirth: '1990-06-30',
    dateOfAppointment: '2015-10-20',
    trainingType: 'JSLC',
    dateOfLastPromotion: '2022-08-01',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1006',
    rank: Rank.JO3,
    lastName: 'Torres',
    firstName: 'Mark',
    middleName: 'Dela Cruz',
    extension: 'Jr',
    gender: 'Male',
    officeAssignment: ['Sogod District Jail'],
    designation: ['Searcher'],
    education: 'BS Education',
    eligibility: 'LET',
    dateOfBirth: '1993-04-18',
    dateOfAppointment: '2017-05-15',
    trainingType: 'JJLC',
    dateOfLastPromotion: '2023-01-10',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1007',
    rank: Rank.JO2,
    lastName: 'Aquino',
    firstName: 'James',
    middleName: 'Bautista',
    extension: '',
    gender: 'Male',
    officeAssignment: ['Tacloban City Jail'],
    designation: ['Custodial Officer'],
    education: 'BS Criminology',
    eligibility: 'RA 1080',
    dateOfBirth: '1995-09-25',
    dateOfAppointment: '2019-11-05',
    trainingType: 'JBRC',
    dateOfLastPromotion: '2023-06-30',
    status: 'Active',
    remarks: ''
  },
  {
    id: 'p-1008',
    rank: Rank.JO1,
    lastName: 'Ramos',
    firstName: 'Liza',
    middleName: 'Gomez',
    extension: '',
    gender: 'Female',
    officeAssignment: ['Regional Office'],
    designation: ['Staff'],
    education: 'BS Accountancy',
    eligibility: 'CPA',
    dateOfBirth: '1998-12-10',
    dateOfAppointment: '2023-03-15',
    trainingType: 'JBRC',
    dateOfLastPromotion: '',
    status: 'Active',
    remarks: 'ON-JBRC-SCHOOLING(15/03/2023)'
  }
];
